AWSTemplateFormatVersion: '2010-09-09'

# Define the resources to be created
Resources:

  MyDBSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: MySecretForAppBrandData
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'

  # RDS PostgreSQL Database Instance
  MyDBInstance:
    Type: 'AWS::RDS::DBInstance'
    DependsOn:
      - MyDBSecret
    Properties:
      AllocatedStorage: '20'
      DBInstanceClass: db.t3.micro # free tier
      Engine: postgres
      EngineVersion: '14.7'
      MasterUsername: brand_data_storage
      MasterUserPassword: '{{resolve:secretsmanager:MySecretForAppBrandData:SecretString:password}}' # Referencing the secret value
      DBInstanceIdentifier: brand-data-db
      StorageType: gp2
      MultiAZ: false
      DBParameterGroupName: !Ref MyDBParameterGroup
    
  MyDBParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Family: postgres14
      Description: My db parameter group
      Parameters:
        # Enable logical replication
        rds.logical_replication: '1'

        # Load shared libraries during database initialization
        shared_preload_libraries: 'pg_stat_statements,pglogical'

  # DMS Replication Instance
  MyDMSInstance:
    Type: 'AWS::DMS::ReplicationInstance'
    Properties:
      ReplicationInstanceClass: dms.t2.micro # free tier
      EngineVersion: 3.4.7
      MultiAZ: false

  # DMS Source Endpoint
  MyDMSSourceEndpoint:
    Type: 'AWS::DMS::Endpoint'
    Properties:
      EndpointIdentifier: my-dms-source-endpoint
      EndpointType: source
      EngineName: postgres
      DatabaseName: brand_data_db
      ServerName: !GetAtt MyDBInstance.Endpoint.Address
      Port: !GetAtt MyDBInstance.Endpoint.Port
      Username: brand_data_storage
      Password: '{{resolve:secretsmanager:my-secrets:SecretString:password}}'
      ExtraConnectionAttributes: 'PluginName=PGLOGICAL;'

  # DMS Target Role
  MyDMSTargetRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: dms.amazonaws.com
            Action: 'sts:AssumeRole'  
      Policies:
        - PolicyName: 'DMSAccessToS3'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
        - PolicyName: 'DMSAccessToRDS'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  # DMS Target Endpoint
  MyDMSTargetEndpoint:
    Type: 'AWS::DMS::Endpoint'
    Properties:
      EndpointIdentifier: my-dms-target-endpoint
      EndpointType: target
      EngineName: s3
      BucketName: !Ref MyS3Bucket

  # S3 Bucket
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'

  # DMS Replication Task
  MyDMSTask:
    Type: 'AWS::DMS::ReplicationTask'
    Properties:
      ReplicationTaskIdentifier: my-dms-task
      MigrationType: full-load-and-cdc
      SourceEndpointArn: !Ref MyDMSSourceEndpoint
      TargetEndpointArn: !Ref MyDMSTargetEndpoint
      ReplicationInstanceArn: !Ref MyDMSInstance
      TableMappings: |
        {
          "rules": [
            {
              "rule-type": "selection",
              "rule-id": "1",
              "rule-name": "rule1",
              "object-locator": {
                "schema-name": "galo_tweets",
                "table-name": "%"
              },
              "rule-action": "include"
            }
          ]
        }
